### ISSUE TITLE
MyBank payment method has no logo

### ISSUE THREAD

**Issue by GodModus** [MultiSafepay/php-sdk#3]
When [Payment Method API](https://docs.multisafepay.com/reference/listpaymentmethods) is used to retrieve all payment methods for some strange reason MyBank is the only payment method that has an empty $data->icon_urls. It should contain 3  image URLs.

**Comment by Daniel-MultiSafepay** [comment]
Hi @GodModus 

Thanks for reach us and your feedback. 

Currently we are not providing support to the "payment-methods" endpoint via the PHP-SDK.
For that reason, your report, even when is valid and clearly something to fix, is not related with this repository or project. 

I want to create a ticket in our internal system. From there, our integration specialist will handle the communication and reply to you; however, in order to include you, and before close this GitHub issue, I need your email.  Also possible, please, write us an email, reporting the exact same issue to support@multisafepay.com. That will go directly to our internal ticket system. 

Thanks.

**Comment by GodModus** [comment]
So let me get this straight. All issues relating to the PHP SDK API must be relayed to customer support?  Quite weird that tech issues are not handled in the depo, but ok then.

**Comment by Daniel-MultiSafepay** [comment]
Hi @GodModus

Like I said, this project, the PHP-SDK, do not provide support for that endpoint. And for the same reason, an issue related with that endpoint do not belong to this place. 

From your reply, I understand you will send an email. Therefore, I`m closing this issue.
