### ISSUE TITLE
Last version of php-http/discovery dependency causes composer to loop

### ISSUE THREAD

**Issue by LeonidasJP** [MultiSafepay/php-sdk#6]
The `php-http/discovery` dependency has been updated today to `v1.15.0`. This version contains a bug that causes `composer update` to end up in an endless loop. See https://github.com/php-http/discovery/issues/211, https://github.com/php-http/discovery/issues/212, https://github.com/php-http/discovery/issues/213

Is it possible to block `php-http/discovery@1.15.0`?

```json
"conflicts": {
    "php-http/discovery": "1.15.0"
}
```

**Comment by nicolas-grekas** [comment]
Wrong call. The right solution is described here: https://github.com/php-http/discovery/issues/213#issuecomment-1424271561

**Comment by Daniel-MultiSafepay** [comment]
Hi @LeonidasJP, thank you for the report.

We have been monitoring this issue closely and it seems a fix is on the way. For now you can use the fix that @nicolas-grekas as a temporary solution until it is fixed in the http/discovery module.

```
  "config": {
    "allow-plugins": {
      "php-http/discovery": false
    }
  }
```

Also, thank you @nicolas-grekas for the quick response and quick [PR](https://github.com/php-http/discovery/pull/214 ) to solve this issue.

**Comment by Daniel-MultiSafepay** [comment]
Hi @LeonidasJP. 

It seems the issue about the endless loop is fixed in the php-http/discovery package at this moment. There is no reason in our side to declare a conflict with that version in the MultiSafepay php-sdk package.

Please, if there is any other feedback on your side, feel free to reopen this issue.
