### ISSUE TITLE
Support `custom_info` when creating a payment page/link

### ISSUE THREAD

**Issue by DaanDeSmedt** [MultiSafepay/php-sdk#8]
As per the documentation provided by MultiSafepay (https://docs.multisafepay.com/reference/createorder) for the Payment page/link, the **custom_info** object allows for the inclusion of extra order-related details.

I've sourced the php-sdk but have not come across any indication of this feature.

To address this gap, I've taken the liberty of creating a quick abstraction to enable support for this feature in my project. It would be greatly appreciated if a native option for this functionality could be integrated into the php-sdk itself.

```php
<?php

declare(strict_types=1);

namespace SDP\Paymentlink\Payment\MultiSafePay;

use InvalidArgumentException;
use MultiSafepay\Api\Transactions\OrderRequest as TransactionsOrderRequest;


class OrderRequest extends TransactionsOrderRequest
{
    /**
     * @var string
     */
    private $recurringModel;

    /**
     * @var array
     */
    private $custom_info;

    /**
     * @param string $type
     * @return OrderRequest
     */
    public function addRecurringModel(string $type): OrderRequest
    {
        if (!in_array($type, self::ALLOWED_RECURRING_MODELS)) {
            $msg = 'Type "' . $type . '" is not a known type. ';
            $msg .= 'Available types: ' . implode(', ', self::ALLOWED_RECURRING_MODELS);
            throw new InvalidArgumentException($msg);
        }

        $this->recurringModel = $type;
        return $this;
    }

    /**
     * @return array
     * phpcs:disable ObjectCalisthenics.Files.FunctionLength
     */
    public function getData(): array
    {
        $data = [
            'type' => $this->type,
            'order_id' => $this->orderId,
            'currency' => $this->money ? (string)$this->money->getCurrency() : null,
            'amount' => $this->money ? (int)round($this->money->getAmount()) : null,
            'gateway' => $this->gatewayCode,
            'gateway_info' => $this->gatewayInfo ? $this->gatewayInfo->getData() : null,
            'payment_options' => $this->paymentOptions ? $this->paymentOptions->getData() : null,
            'description' => ($this->description) ? $this->description->getData() : null,
            'recurring_id' => $this->recurringId ?? null,
            'recurring_model' => $this->recurringModel ?? null,
            'google_analytics' => $this->googleAnalytics ? $this->googleAnalytics->getData() : null,
            'second_chance' => $this->secondChance ? $this->secondChance->getData() : null,
            'customer' => ($this->customer) ? $this->customer->getData() : null,
            'delivery' => $this->delivery ? $this->delivery->getData() : null,
            'shopping_cart' => $this->shoppingCart ? $this->shoppingCart->getData() : null,
            'checkout_options' => $this->checkoutOptions ? $this->checkoutOptions->getData() : null,
            'days_active' => $this->daysActive,
            'seconds_active' => $this->secondsActive,
            'plugin' => $this->pluginDetails ? $this->pluginDetails->getData() : null,
            'custom_info' => $this->custom_info
        ];

        $data = $this->removeNullRecursive(array_merge($data, $this->data));
        $this->validate($data);

        return $data;
    }

    /**
       * @param string $type
       * @return OrderRequest
       */
    public function addCustomInfo(array $custom_info): OrderRequest
    {
        $count = 1;
        $this->custom_info = [];
        foreach ($custom_info as $value) {
            $this->custom_info["custom_" . $count] = $value;
            $count++;
        }
        return $this;
    }

}
```

**Comment by CasEbb** [comment]
The same case also applies to `var1` to `var3`. Strangely enough, getter methods are present in `\MultiSafepay\Api\Transactions\TransactionResponse` but setter methods lack in `\MultiSafepay\Api\Transactions\OrderRequest`

**Comment by Daniel-MultiSafepay** [comment]
Thanks for your comments and join this discussion @CasEbb 

- A few days ago @DaanDeSmedt submitted a contribution to add support for the custom_info, and we just merged that in the master branch.  We will release a new version, in the next few days including this feature. 

- We just created a backlog item to do something similar to support in a clean way var1 - var3 variables. We will work on that in the next few days. 

====

For both objects, there is a "workaround" that we have been using in many integrations, without the need to add a new object to handle this, even when, as both of you, we agreed the way to go will be to create an object for this. 

Allow me to explain how you can immediately work with this, without adding a new object to the PHP-SDK. 

**The OrderRequest object extends from RequestBody object.**
https://github.com/MultiSafepay/php-sdk/blob/master/src/Api/Transactions/OrderRequest.php#L30C34-L30C34

**The RequestBody object extends from DataObject object.**
https://github.com/MultiSafepay/php-sdk/blob/master/src/Api/Base/RequestBody.php#L15C7-L15C18

**In the DataObject there is a method called addData();**
https://github.com/MultiSafepay/php-sdk/blob/master/src/Api/Base/DataObject.php#L13


Using this method, you should be capable to use something like var1 - var 3 into the orderRequest object.

It will be something like: 

```
use MultiSafepay\Api\Transactions\OrderRequest;

$orderRequest = new OrderRequest();
$orderRequest->addData( 
  array( 'var1' => 'Var 1 Example' ) 
);
```

In the same way, you should be able to catch anything from the transaction response, even if there is no get method for it, using something like:

```
MultiSafepay\Api\Transactions\TransactionResponse::get('var1');
```

For the moment, I am going to close this GitHub issue as resolved because of the PR we just merged. But feel free to reopen it, or open a new one if you want to continue talking about this, or anything else. 

Once again, thanks to both of you for contacting us, and to @DaanDeSmedt for his contribution to this project.
